config/routes.rb
Rails.application.routes.draw do
  root 'mint#index'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'
  get 'login', to: redirect('/users/sign_in')

  resources :account, only: [:index, :update]
  resources :projects, only: [:edit, :update]

  resources :smart_contracts, only: [:new, :show, :update, :create]
  get 'verifying', to: 'smart_contracts#verifying'
  patch 'verify', to: 'smart_contracts#verify'
  patch 'check', to: 'smart_contracts#check'

  resources :mint, only: [:index]

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end
end

app/views/shared/_flash.html.erb
<div class="md:grid md:grid-cols-3 md:gap-6">
  <div class="md:col-span-1"></div>
  <div class="md:col-span-1">
    <% if flash[:alert].present? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
        <strong class="font-bold">Uh oh!</strong>
        <span class="block sm:inline"><%= alert %></span>
        <span id="flash_alert_close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
        </span>
      </div>
    <% end %>

    <% if flash[:notice].present? %>
    <div class="bg-lightgreen-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Cool!</strong>
      <span class="block sm:inline"><%= notice %></span>
      <span id="flash_alert_close" class="absolute top-0 bottom-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
      </span>
    </div>
    <% end %>
  </div>
</div>

<!-- Flash management -->
<script type="text/javascript">
  var flashAlert = document.getElementById('flash_alert_close');
  if (flashAlert !== null) {
    document.getElementById('flash_alert_close').addEventListener('click', function() {
      this.parentElement.remove();
    });
  }
</script>

app/views/shared/_footer.html.erb
<footer class="relative">
  <div class="mx-auto px-4 mt-12">
    <div class="flex flex-col md:flex-row justify-between items-center md:justify-center md:space-x-10">
      <div class="flex justify-center lg:w-0 lg:flex-1">
        <% if params[:controller] == 'mint' %>
          <div id="language-picker-container" class="hidden">
            <select id="language-picker" name="language-selector" class="bg-indigo-100 px-2 py-1 rounded" style="background-image: none;">
              <option data-language-id="ko">🇰🇷</option>
              <option selected data-language-id="en">🇺🇸</option>
            </select>
          </div>
        <% else %>
          <a href="<%= root_path %>" class="flex items-center">
            <%= render partial: 'shared/ooju/logo' %>
          </a>
        <% end %>
      </div>
    </div>
  </div>

  <div class="mt-6 pb-5 px-4 text-center relative">
    <p class="text-xs tracking-wider text-black">Provided by <%= link_to 'Ooju', 'https://ooju.xyz', target: :_blank %>, <%= Date.today.year %></p>
  </div>

  <!-- <div class="flex space-x-6 justify-center mb-12">
    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">Facebook</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
      </svg>
    </a>

    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">Instagram</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
      </svg>
    </a>

    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">Twitter</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
      </svg>
    </a>

    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">YouTube</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <title>YouTube</title>
        <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
      </svg>
    </a>

    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">Reddit</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path d="M24 11.779c0-1.459-1.192-2.645-2.657-2.645-.715 0-1.363.286-1.84.746-1.81-1.191-4.259-1.949-6.971-2.046l1.483-4.669 4.016.941-.006.058c0 1.193.975 2.163 2.174 2.163 1.198 0 2.172-.97 2.172-2.163s-.975-2.164-2.172-2.164c-.92 0-1.704.574-2.021 1.379l-4.329-1.015c-.189-.046-.381.063-.44.249l-1.654 5.207c-2.838.034-5.409.798-7.3 2.025-.474-.438-1.103-.712-1.799-.712-1.465 0-2.656 1.187-2.656 2.646 0 .97.533 1.811 1.317 2.271-.052.282-.086.567-.086.857 0 3.911 4.808 7.093 10.719 7.093s10.72-3.182 10.72-7.093c0-.274-.029-.544-.075-.81.832-.447 1.405-1.312 1.405-2.318zm-17.224 1.816c0-.868.71-1.575 1.582-1.575.872 0 1.581.707 1.581 1.575s-.709 1.574-1.581 1.574-1.582-.706-1.582-1.574zm9.061 4.669c-.797.793-2.048 1.179-3.824 1.179l-.013-.003-.013.003c-1.777 0-3.028-.386-3.824-1.179-.145-.144-.145-.379 0-.523.145-.145.381-.145.526 0 .65.647 1.729.961 3.298.961l.013.003.013-.003c1.569 0 2.648-.315 3.298-.962.145-.145.381-.144.526 0 .145.145.145.379 0 .524zm-.189-3.095c-.872 0-1.581-.706-1.581-1.574 0-.868.709-1.575 1.581-1.575s1.581.707 1.581 1.575-.709 1.574-1.581 1.574z"/>
      </svg>
    </a>

    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">GitHub</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
      </svg>
    </a>

    <a href="#" class="text-gray-400 hover:text-gray-500" target="_blank">
      <span class="sr-only">Dribbble</span>
      <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
        <path fill-rule="evenodd" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z" clip-rule="evenodd" />
      </svg>
    </a>
  </div> -->
</footer>

app/views/shared/_header.html.erb
<header class="absolute top-0 left-0 w-full z-20" data-controller="header">
  <div class="mx-auto px-5">
    <div class="flex justify-between items-center py-5 md:justify-start md:space-x-6 xl:space-x-10">
      <div class="flex justify-start xl:w-0 md:flex-1">
        <a href="<%= root_path %>" class="flex items-center">
          <%= render partial: 'shared/ooju/logo', locals: { header: true } %>
          <span class="sr-only"><%= Project::DEFAULT_NAME %></span>
        </a>
      </div>
      <!-- <div class="flex md:hidden" data-action="click->header#toggleMobileNav">
        <button type="button" class="p-2 inline-flex items-center justify-center text-black-100 focus:outline-none js--navbar-burger">
          <span class="sr-only">Open menu</span>

          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
          </svg>
        </button>
      </div> -->
      <nav class="hidden md:flex space-x-4 sm:space-x-6 lg:space-x-10 text-base">
        <% if current_user && current_user.admin? %>
          <%= link_to 'Mint', mint_index_path, data: { turbo: false } %>
          <%= link_to 'Project', edit_project_path(Project::CURRENT.id) %>
          <%= link_to 'Account', account_index_path %>
          <%= link_to 'Logout', logout_path %>
        <% end %>
      </nav>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on mobile menu state. -->
  <!-- <div id="main-nav" data-header-target="mainNav" class="absolute top-0 inset-x-0 transition transform origin-top-right md:hidden z-10 duration-200 ease-in-out opacity-0 hidden">
    <div class="bg-white drop-shadow-2xl">
      <div class="p-4">
        <div class="flex flex-row-reverse">
          <button type="button" data-action="click->header#toggleMobileNav" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500 js--navbar-burger">
            <span class="sr-only">Close menu</span>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <nav class="grid">
          <a href="/" class="text-center p-4">
            Home
          </a>
          <a href="/terms" class="text-center p-4">
            Terms
          </a>
        </nav>
      </div>
    </div>
  </div> -->
</header>

<!-- smooth scroll nav links -->
<script type="text/javascript">
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function (e) {
          e.preventDefault();

          document.querySelector(this.getAttribute('href')).scrollIntoView({
              behavior: 'smooth'
          });
      });
  });
</script>

app/views/shared/_heading.html.erb
<% description ||= '' %>
<div class="mt-14 text-center mb-4">
  <h1 class="mt-1 font-extrabold text-gray-900 text-4xl sm:text-4xl sm:tracking-tight lg:text-5xl"><%= title %></h1>
  <p class="max-w-xl mt-5 mx-auto text-xl text-gray-500"><%= description.html_safe %></p>
</div>

app/views/shared/_heading_web3.html.erb
<% title_intro ||= nil %>
<% title ||= nil %>
<% additional_text ||= nil %>

<div>
  <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
    <div class="text-center">
      <h2 style="min-height: 24px" class="text-base font-semibold text-indigo-600 tracking-wide uppercase"><%= title_intro %></h2>
      <p id="label-title" class="mt-1 text-4xl font-extrabold text-gray-900 sm:text-5xl sm:tracking-tight lg:text-6xl"><%= title %></p>
      <p id="label-description" class="max-w-xl mt-5 mx-auto text-xl text-gray-500">
        <%= additional_text %>
      </p>
      <p id="mint-progress-counter" style="min-height: 20px" class="max-w-xl mt-2 mx-auto text-sm text-gray-500"></p>
    </div>
  </div>
</div>

app/views/shared/_logo.html.erb
<svg class="text-primary" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 35 32" width="35" height="32">
  <path fill="currentColor" d="M15.258 26.865a4.043 4.043 0 01-1.133 2.917A4.006 4.006 0 0111.253 31a3.992 3.992 0 01-2.872-1.218 4.028 4.028 0 01-1.133-2.917c.009-.698.2-1.382.557-1.981.356-.6.863-1.094 1.47-1.433-.024.109.09-.055 0 0l1.86-1.652a8.495 8.495 0 002.304-5.793c0-2.926-1.711-5.901-4.17-7.457.094.055-.036-.094 0 0A3.952 3.952 0 017.8 7.116a3.975 3.975 0 01-.557-1.98 4.042 4.042 0 011.133-2.918A4.006 4.006 0 0111.247 1a3.99 3.99 0 012.872 1.218 4.025 4.025 0 011.133 2.917 8.521 8.521 0 002.347 5.832l.817.8c.326.285.668.551 1.024.798.621.33 1.142.826 1.504 1.431a3.902 3.902 0 01-1.504 5.442c.033-.067-.063.036 0 0a8.968 8.968 0 00-3.024 3.183 9.016 9.016 0 00-1.158 4.244zM19.741 5.123c0 .796.235 1.575.676 2.237a4.01 4.01 0 001.798 1.482 3.99 3.99 0 004.366-.873 4.042 4.042 0 00.869-4.386 4.02 4.02 0 00-1.476-1.806 3.994 3.994 0 00-5.058.501 4.038 4.038 0 00-1.175 2.845zM23.748 22.84c-.792 0-1.567.236-2.226.678a4.021 4.021 0 00-1.476 1.806 4.042 4.042 0 00.869 4.387 3.99 3.99 0 004.366.873A4.01 4.01 0 0027.08 29.1a4.039 4.039 0 00-.5-5.082 4 4 0 00-2.832-1.18zM34 15.994c0-.796-.235-1.574-.675-2.236a4.01 4.01 0 00-1.798-1.483 3.99 3.99 0 00-4.367.873 4.042 4.042 0 00-.869 4.387 4.02 4.02 0 001.476 1.806 3.993 3.993 0 002.226.678 4.003 4.003 0 002.832-1.18A4.04 4.04 0 0034 15.993z"/>
  <path fill="currentColor" d="M5.007 11.969c-.793 0-1.567.236-2.226.678a4.021 4.021 0 00-1.476 1.807 4.042 4.042 0 00.869 4.386 4.001 4.001 0 004.366.873 4.011 4.011 0 001.798-1.483 4.038 4.038 0 00-.5-5.08 4.004 4.004 0 00-2.831-1.181z"/>
</svg>

<% if false %>
  <%= image_tag "avatar.png",  style: "max-height: 42px" %>
<% end %>

app/views/shared/_seo_head.html.erb
<!-- Site | Title -->
<% meta title: @setup[:title] %>

<!-- Open Graph -->
<meta property="og:locale" content="en">
<meta property="og:type" content="website">
<meta property="og:title" content="<%= Project::DEFAULT_NAME %> | <%= @setup[:title] %>">
<meta property="og:description" content="<%= @setup[:description] %>">
<meta property="og:site_name" content="<%= Project::DEFAULT_NAME %>">
<meta property="og:image" content="<%= @setup[:og_image] %>">
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="640" />

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<%= Project::DEFAULT_NAME %> | <%= @setup[:title] %>">
<meta name="twitter:image" content="<%= @setup[:og_image] %>">